# Generated by Django 4.1.7 on 2023-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Menu Item Slug'),
        ),
    ]
